version: "3"
services:
  server:
    build:
      context: ../../
      dockerfile: docker/dev/Dockerfile
    container_name: sms-management-api
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ../../:/app
